name: Continuous Integration

on: [push]

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x] # see: https://vercel.com/mrtnzlml/meta/settings

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn dependencies
        # Command `yarn install --frozen-lockfile` doesn't always fail if `yarn.lock` is modified (https://github.com/yarnpkg/yarn/issues/5840).
        # Instead, we are installing the dependencies as usual and checking that nothing changed.
        run: |
          yarn install
          git diff --exit-code

      - name: Run Eslint
        run: yarn run lint
